//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBillBorrow
    {
        public int idDetailBillBorrow { get; set; }
        public int idBook { get; set; }
        public int idBillBorrow { get; set; }
        public int returned { get; set; }
    
        public virtual BillBorrow BillBorrow { get; set; }
        public virtual Book Book { get; set; }
    }
}
