//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int idPayment { get; set; }
        public int idReader { get; set; }
        public int currentDebt { get; set; }
        public int collectedAmount { get; set; }
        public int remainDebt { get; set; }
        public System.DateTime paymentDate { get; set; }
    
        public virtual Reader Reader { get; set; }
    }
}
