//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reader()
        {
            this.BillBorrows = new HashSet<BillBorrow>();
            this.BillReturns = new HashSet<BillReturn>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int idReader { get; set; }
        public string nameReader { get; set; }
        public System.DateTime dobReader { get; set; }
        public string email { get; set; }
        public string addressReader { get; set; }
        public System.DateTime createdAt { get; set; }
        public int debt { get; set; }
        public System.DateTime latestExtended { get; set; }
        public int idTypeReader { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillBorrow> BillBorrows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReturn> BillReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual TypeReader TypeReader { get; set; }
    }
}
