//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int idStaff { get; set; }
        public string nameStaff { get; set; }
        public System.DateTime dobStaff { get; set; }
        public string addressStaff { get; set; }
        public string phoneNumberStaff { get; set; }
        public string accountStaff { get; set; }
        public string passwordStaff { get; set; }
        public int idPermission { get; set; }
    
        public virtual Permission Permission { get; set; }
    }
}
